// @ts-check

// type CardValue = "A" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "X" | "J" | "Q" | "K";
// type Suit = "spade" | "heart" | "diamond" | "club";
// interface Card {
//     value: CardValue;
//     suit: Suit;
// }

import { cardHeight, cardWidth } from "./card.js";
import { drawPileLocation } from "./positions.js";
import { numberToPixel } from "./utils.js";

/**
 * A card value.
 * @typedef {("A" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "X" | "J" | "Q" | "K")} CardValue
 */

/**
 * A card suit.
 * @typedef {("spade" | "heart" | "diamond" | "club")} Suit
 */

/**
 * A card.
 * @typedef {{value: CardValue, suit: Suit}} Card
 */

/**
 * An array of all card values
 *
 * @constant
 * @type {CardValue[]}
 */
const cardValues = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "X", "J", "Q", "K"];


/**
 * An array of all suits.
 *
 * @constant
 * @type {Suit[]}
*/
export const suits = ["spade", "heart", "diamond", "club"];


/**
 * An array representing a full deck of playing cards.
 * Each card is an object with a `value` (e.g., 'A', '2', ..., 'K') and a `suit`.
 * The deck is generated by combining each card value with each suit from the `suits` array.
 *
 * @constant
 * @type {Card[]}
 */
export const totalDeck = cardValues.flatMap((cardValue) =>
    suits.map((suit) => ({
        value: cardValue,
        suit: suit,
    }))
);

/**
 * An array of URLs pointing to SVG images of English pattern playing cards.
 * These images are from the public domain.
 *
 * @type {string[]}
 */
const cardImageUrls = [
    "https://upload.wikimedia.org/wikipedia/commons/1/19/English_pattern_ace_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d4/English_pattern_ace_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/00/English_pattern_ace_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/5/5f/English_pattern_ace_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/0b/English_pattern_2_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/26/English_pattern_2_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/99/English_pattern_2_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/3/30/English_pattern_2_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/a/a5/English_pattern_3_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/0f/English_pattern_3_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/2c/English_pattern_3_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/14/English_pattern_3_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/3/34/English_pattern_4_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/bb/English_pattern_4_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/4e/English_pattern_4_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/c/c0/English_pattern_4_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/9c/English_pattern_5_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/c/c6/English_pattern_5_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/6/6c/English_pattern_5_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/7/74/English_pattern_5_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/a/ac/English_pattern_6_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/da/English_pattern_6_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/4e/English_pattern_6_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/02/English_pattern_6_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d1/English_pattern_7_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/c/cb/English_pattern_7_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/5/5d/English_pattern_7_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/6/60/English_pattern_7_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/4d/English_pattern_8_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/3/3c/English_pattern_8_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/18/English_pattern_8_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f0/English_pattern_8_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f0/English_pattern_9_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/22/English_pattern_9_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f5/English_pattern_9_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/14/English_pattern_9_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/da/English_pattern_10_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/bb/English_pattern_10_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/da/English_pattern_10_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/48/English_pattern_10_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/4f/English_pattern_jack_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/5/56/English_pattern_jack_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/16/English_pattern_jack_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/8/80/English_pattern_jack_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/c/ca/English_pattern_queen_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/9d/English_pattern_queen_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/4f/English_pattern_queen_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b3/English_pattern_queen_of_clubs.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f1/English_pattern_king_of_spades.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/14/English_pattern_king_of_hearts.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/1c/English_pattern_king_of_diamonds.svg",
    "https://upload.wikimedia.org/wikipedia/commons/3/3e/English_pattern_king_of_clubs.svg",
];

export function getCardImageUrl(card) {
    let idx = totalDeck.findIndex(
        (c) => c.value == card.value && c.suit == card.suit
    );
    if (idx === -1) {
        return "";
    } else {
        return cardImageUrls[idx];
    }
}

/**
 * Gets the card id of a card.
 * 
 * @param {Card} card 
 * @returns {string}
 */
export function getCardId(card) {
    return [card.value, card.suit].join("-");
}

/**
 * Gets the face value of a card
 * 
 * @param {Card} card 
 * @returns 
 */
export function getValue(card) {
    switch (card.value) {
        case "A":
            return 1;
        case "2":
            return 2;
        case "3":
            return 3;
        case "4":
            return 4;
        case "5":
            return 5;
        case "6":
            return 6;
        case "7":
            return 7;
        case "8":
            return 8;
        case "9":
            return 9;
        case "X":
            return 10;
        case "J":
            return 11;
        case "Q":
            return 12;
        case "K":
            return 13;
    }
}